<a href="https://colab.research.google.com/github/HumamAqeelBudiana/data-science-toolkit/blob/main/TutorialDataScienceW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a numpy array of size 2 x 2

In [ ]:
import numpy as napy
N1=napy.array([[2,3],[1,8]])
print(N1)

[[2 3]
 [1 8]]


2. Create a random numpy array of size 3 x 4

In [ ]:
N2=napy.random.random((3,4))
print(N2)

[[0.56937242 0.15768049 0.87827883 0.14847099]
 [0.43778415 0.9542833  0.38551835 0.18117835]
 [0.54225456 0.24693664 0.43288293 0.3863534 ]]


3. Create a numpy array of ones and a numpy array of zeroes

In [ ]:
N3=napy.ones((2,2))
print(N3)
N4=napy.zeros((2,2))
print(N4)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [ ]:
N5=napy.random.random((6,3))
print("Original Numpy:")
print(N5)


transpose=N5.T
print("Transposed Numpy")
print(transpose)

Original Numpy:
[[0.76028164 0.53684048 0.96856575]
 [0.24556422 0.75795842 0.21610598]
 [0.50904981 0.18803669 0.16443888]
 [0.48643181 0.94141362 0.75116897]
 [0.07731242 0.27122715 0.67980194]
 [0.8796701  0.20496503 0.99891594]]
Transposed Numpy
[[0.76028164 0.24556422 0.50904981 0.48643181 0.07731242 0.8796701 ]
 [0.53684048 0.75795842 0.18803669 0.94141362 0.27122715 0.20496503]
 [0.96856575 0.21610598 0.16443888 0.75116897 0.67980194 0.99891594]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [ ]:
n, p, m = 2, 4, 6

A = napy.random.rand(n, p)
B = napy.random.rand(p, m)

print("Matrix A (n x p):")
print(A)
print("Matrix B (p x m):")
print(B)

C = napy.dot(A, B)
print("Dot Product (A · B) = C (n x m):")
print(C)


Matrix A (n x p):
[[0.07489564 0.25152114 0.33675078 0.81706714]
 [0.91950499 0.94284295 0.2470168  0.85778946]]
Matrix B (p x m):
[[0.59921673 0.31966215 0.74114071 0.34115014 0.85829986 0.20171353]
 [0.84281991 0.6779806  0.21842753 0.69381885 0.29014889 0.05235773]
 [0.20229894 0.61472241 0.16916512 0.30204372 0.29559841 0.82749658]
 [0.24163103 0.70022942 0.60939524 0.69657618 0.04269823 0.69022779]]
Dot Product (A · B) = C (n x m):
[[0.52241884 0.97361045 0.66533066 0.87092373 0.27169181 0.87089911]
 [1.60286937 1.68565634 1.45194488 1.63997704 1.17241971 1.0313174 ]]
